"""empty message

Revision ID: 0f282f56e450
Revises: c228dbca2a94
Create Date: 2021-01-28 11:35:02.740416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f282f56e450'
down_revision = 'c228dbca2a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'name')
    # ### end Alembic commands ###
