"""empty message

Revision ID: 40fe5dd422e7
Revises: c0909c1db3ba
Create Date: 2021-02-04 15:58:24.552742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40fe5dd422e7'
down_revision = 'c0909c1db3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('gen', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artist', 'gen')
    # ### end Alembic commands ###
