"""empty message

Revision ID: ce2dff6c7377
Revises: 40fe5dd422e7
Create Date: 2021-02-04 15:59:12.552182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce2dff6c7377'
down_revision = '40fe5dd422e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('artist', 'gen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('gen', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###
